<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-23T18:08:04 IST" name="Login Test Suite" finished-at="2025-05-23T18:09:40 IST" duration-ms="96050">
    <groups>
    </groups>
    <test started-at="2025-05-23T18:08:04 IST" name="Login Chrome Test Suite" finished-at="2025-05-23T18:08:53 IST" duration-ms="49104">
      <class name="testClasses.TC_login_WrongPassword">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testClasses.TC_login_WrongPassword@7f3b84b8]" started-at="2025-05-23T18:08:36 IST" name="setup" finished-at="2025-05-23T18:08:43 IST" duration-ms="6221" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:testClasses.TC_login_WrongPassword@7f3b84b8]" started-at="2025-05-23T18:08:43 IST" name="login" finished-at="2025-05-23T18:08:53 IST" duration-ms="10330" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login succeeded or unexpected behavior: Your password is invalid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login succeeded or unexpected behavior: Your password is invalid!
at org.testng.Assert.fail(Assert.java:111)
at testClasses.TC_login_WrongPassword.login(TC_login_WrongPassword.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.TC_login_WrongPassword@7f3b84b8]" started-at="2025-05-23T18:08:53 IST" name="tearDown" finished-at="2025-05-23T18:08:53 IST" duration-ms="205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.TC_login_WrongPassword -->
      <class name="testClasses.TC_001_Login">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testClasses.TC_001_Login@36902638]" started-at="2025-05-23T18:08:04 IST" name="setup" finished-at="2025-05-23T18:08:16 IST" duration-ms="11620" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:testClasses.TC_001_Login@36902638]" started-at="2025-05-23T18:08:16 IST" name="login" finished-at="2025-05-23T18:08:18 IST" duration-ms="1411" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.TC_001_Login@36902638]" started-at="2025-05-23T18:08:18 IST" name="tearDown" finished-at="2025-05-23T18:08:18 IST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.TC_001_Login -->
      <class name="testClasses.TC_login_WrongUserName">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testClasses.TC_login_WrongUserName@77847718]" started-at="2025-05-23T18:08:18 IST" name="setup" finished-at="2025-05-23T18:08:24 IST" duration-ms="6085" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:testClasses.TC_login_WrongUserName@77847718]" started-at="2025-05-23T18:08:24 IST" name="login" finished-at="2025-05-23T18:08:34 IST" duration-ms="10366" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login succeeded or unexpected behavior: ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login succeeded or unexpected behavior: 
at org.testng.Assert.fail(Assert.java:111)
at testClasses.TC_login_WrongUserName.login(TC_login_WrongUserName.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.TC_login_WrongUserName@77847718]" started-at="2025-05-23T18:08:35 IST" name="tearDown" finished-at="2025-05-23T18:08:36 IST" duration-ms="1769" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.TC_login_WrongUserName -->
    </test> <!-- Login Chrome Test Suite -->
    <test started-at="2025-05-23T18:08:54 IST" name="Login Edge Test Suite" finished-at="2025-05-23T18:09:40 IST" duration-ms="46553">
      <class name="testClasses.TC_login_WrongPassword">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testClasses.TC_login_WrongPassword@6302bbb1]" started-at="2025-05-23T18:09:23 IST" name="setup" finished-at="2025-05-23T18:09:29 IST" duration-ms="6039" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:testClasses.TC_login_WrongPassword@6302bbb1]" started-at="2025-05-23T18:09:29 IST" name="login" finished-at="2025-05-23T18:09:39 IST" duration-ms="10304" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login succeeded or unexpected behavior: ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login succeeded or unexpected behavior: 
at org.testng.Assert.fail(Assert.java:111)
at testClasses.TC_login_WrongPassword.login(TC_login_WrongPassword.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.TC_login_WrongPassword@6302bbb1]" started-at="2025-05-23T18:09:39 IST" name="tearDown" finished-at="2025-05-23T18:09:40 IST" duration-ms="1211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.TC_login_WrongPassword -->
      <class name="testClasses.TC_001_Login">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testClasses.TC_001_Login@2a65fe7c]" started-at="2025-05-23T18:08:54 IST" name="setup" finished-at="2025-05-23T18:09:02 IST" duration-ms="8042" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:testClasses.TC_001_Login@2a65fe7c]" started-at="2025-05-23T18:09:02 IST" name="login" finished-at="2025-05-23T18:09:03 IST" duration-ms="1430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.TC_001_Login@2a65fe7c]" started-at="2025-05-23T18:09:03 IST" name="tearDown" finished-at="2025-05-23T18:09:05 IST" duration-ms="1263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.TC_001_Login -->
      <class name="testClasses.TC_login_WrongUserName">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testClasses.TC_login_WrongUserName@4135c3b]" started-at="2025-05-23T18:09:05 IST" name="setup" finished-at="2025-05-23T18:09:11 IST" duration-ms="6190" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:testClasses.TC_login_WrongUserName@4135c3b]" started-at="2025-05-23T18:09:11 IST" name="login" finished-at="2025-05-23T18:09:21 IST" duration-ms="10319" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login succeeded or unexpected behavior: Your username is invalid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login succeeded or unexpected behavior: Your username is invalid!
at org.testng.Assert.fail(Assert.java:111)
at testClasses.TC_login_WrongUserName.login(TC_login_WrongUserName.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testClasses.TC_login_WrongUserName@4135c3b]" started-at="2025-05-23T18:09:21 IST" name="tearDown" finished-at="2025-05-23T18:09:23 IST" duration-ms="1360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testClasses.TC_login_WrongUserName -->
    </test> <!-- Login Edge Test Suite -->
  </suite> <!-- Login Test Suite -->
</testng-results>
